trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pip install coverage
  displayName: 'Install dependencies'

- script: |
    python src/manage.py test
  displayName: 'Run tests'

- script: |
    coverage run src/manage.py test
    coverage report || true
  displayName: 'Run tests with coverage'
